[2025-08-01 14:34:23,380] 12 utils.logging - INFO - downloading data from kaggle...
[2025-08-01 14:34:25,341] 16 utils.logging - INFO - saving raw data...
[2025-08-01 14:34:25,413] 20 utils.logging - INFO - splitting into train, test and validation
[2025-08-01 14:34:25,421] 23 utils.logging - INFO - saving train, test and validation
[2025-08-01 14:34:25,528] 20 utils.logging - INFO - Running preprocessing pipeline...
[2025-08-01 14:34:25,529] 80 utils.logging - INFO - Starting preprocessing pipeline...
[2025-08-01 14:34:25,529] 22 utils.logging - INFO - Reading training data for imbalance handling...
[2025-08-01 14:34:25,598] 27 utils.logging - INFO - Handling imbalance using RandomOverSampler...
[2025-08-01 14:34:25,609] 43 utils.logging - INFO - Building preprocessor pipeline...
[2025-08-01 14:34:25,609] 92 utils.logging - INFO - Fitting and transforming training data...
[2025-08-01 14:34:25,632] 97 utils.logging - INFO - Fitted preprocessor saved at model/preprocessor.pkl
[2025-08-01 14:34:25,780] 119 utils.logging - INFO - Saved preprocessed X to data/processed/X_processed.csv
[2025-08-01 14:34:25,781] 120 utils.logging - INFO - Saved target y to data/processed/y.csv
[2025-08-01 14:34:25,781] 23 utils.logging - INFO - Training model ....
[2025-08-01 14:34:25,782] 19 utils.logging - INFO - \U0001f4e5 Loading training data...
[2025-08-01 14:34:25,843] 23 utils.logging - INFO - \U0001f680 Starting MLflow run...
[2025-08-01 14:34:51,450] 46 utils.logging - INFO - \u2705 RandomForestClassifier trained and logged to MLflow.
[2025-08-01 14:34:51,461] 26 utils.logging - INFO - Evaluating the model
[2025-08-01 14:34:51,461] 12 utils.logging - INFO - \U0001f50d Loading validation data...
[2025-08-01 14:34:51,504] 17 utils.logging - INFO - \U0001f4e6 Loading preprocessor and transforming validation data...
[2025-08-01 14:34:51,509] 29 utils.logging - INFO - \U0001f4e5 Loading best model from MLflow...
[2025-08-01 14:34:51,546] 69 utils.logging - ERROR - \u274c Error occurred during evaluation.
Traceback (most recent call last):
  File "C:\Users\Hp\Desktop\CustomerChurn\src\components\evaluation.py", line 31, in evaluate_model
    model = mlflow.sklearn.load_model(logged_model_uri)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\mlflow\sklearn\__init__.py", line 633, in load_model
    local_model_path = _download_artifact_from_uri(artifact_uri=model_uri, output_path=dst_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\mlflow\tracking\artifact_utils.py", line 116, in _download_artifact_from_uri
    return repo.download_artifacts(artifact_path=artifact_path, dst_path=output_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\mlflow\store\artifact\runs_artifact_repo.py", line 131, in download_artifacts
    return self.repo.download_artifacts(artifact_path, dst_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\mlflow\store\artifact\local_artifact_repo.py", line 91, in download_artifacts
    raise OSError(f"No such file or directory: '{local_artifact_path}'")
OSError: No such file or directory: 'C:\Users\Hp\Desktop\CustomerChurn\mlruns\0\e46baa8433bc4b47b3625bc038121d22\artifacts\model'
